apiVersion: v1
kind: Service
metadata:
  name: sentry-web-service
  namespace: gopikab
spec:
  selector:
    app: sentry
    release: sentry
    role: web
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080