FROM --platform=linux/amd64 acryldata/datahub-actions:v0.0.13

USER root

# -- Layer: Apache Spark

ARG spark_version=3.0.3
ARG hadoop_version=3.2

RUN curl -sS https://archive.apache.org/dist/spark/spark-${spark_version}/spark-${spark_version}-bin-hadoop${hadoop_version}.tgz -o spark.tgz && \
    tar -xf spark.tgz && \
    mv spark-${spark_version}-bin-hadoop${hadoop_version} /usr/bin/ && \
    mkdir /usr/bin/spark-${spark_version}-bin-hadoop${hadoop_version}/logs && \
    rm spark.tgz && \
    rm -rf /var/tmp/* /tmp/* /var/lib/apt/lists/*

RUN set -e; \
    pip install JPype1

ENV PYSPARK_PYTHON python3.10
ENV PATH=$PATH:$SPARK_HOME/bin

USER datahub